FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PR Roulette

PR Roulette is a simple API that allows teams a randomized peer review process.

## Team Collection [api/public/team/view/:id]

Pass in team ID to get the team and information

### List Team [GET]

+ Response 200 (application/json)

        [
            {
              "success": true,
              "data": {
                "_id": "583378ab846b2c0010eb410d",
                "owner": "phillip.chan@liferay.com",
                "settings": {
                  "name": "LR Web Team"
                },
                "__v": 23,
                "members": [
                  {
                    "name": "Luke"
                  },
                  {
                    "name": "Allen"
                  },
                  {
                    "name": "Weston"
                  },
                  {
                    "name": "Phil"
                  },
                  {
                    "name": "Rebecca"
                  }
                ]
              }
            }
        ]

## Team Search [api/public/teams/search]

Pass in team ID to get the team and information

### Search for Team [GET]

You may search for teams with this action. It takes a search term in the header and returns a list of teams that match that search query.

+ Request (application/json)

        {
            "headers": {
                teamname: "Your search query"
            }
        }

+ Response 201 (application/json)

    + Body

        [
          {
            "_id": "583378ed846b2c0010eb410f",
            "owner": "weston.hancock@liferay.com",
            "settings": {
              "name": "New Team"
            },
            "__v": 0,
            "members": []
          }
        ]